In [24]:
import numpy as np
import pandas as pd

In [25]:
df=pd.read_csv(r'C:\Users\Swarupa V\Desktop\watchnext\dataset\datasets_1474_2639_IMDB-Movie-Data.csv')

In [26]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,NaN
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,NaN
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,NaN
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,NaN
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,NaN

In [27]:
df['Metascore'].fillna(1,inplace=True)
df.head(30)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,NaN
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,NaN
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,NaN
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,NaN
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,NaN
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0,NaN
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0,NaN
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0,NaN
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0,NaN
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0,NaN
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0,NaN
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0,NaN
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0,NaN
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0,NaN
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0,NaN
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0,NaN
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0,NaN
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0,NaN
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0,NaN
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0,NaN
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0,NaN
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0,NaN
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0,NaN
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0,NaN
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0,NaN
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,1.0,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,1.0,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,1.0,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0,NaN
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0,NaN

In [28]:
action=[]
drama=[]
thriller=[]
adventure=[]
comedy=[]
horror=[]
biography=[]
animation=[]
scifi=[]
romance=[]
others=[]

In [29]:
#to get a list of all movies in all genre
genres=list(df["Genre"].values)
movies=list(df["Title"])
i=0
for genre,movie in zip(genres,movies):
    lst=genre.split(',')
    for g in lst:
        if(g=="Action" or g=='War'):
            action.append(movie)
        if(g=='Drama' or g=='Musical' or g=='Family'):
            drama.append(movie)
        if(g=='Thriller' or g=='Crime' or g=='Mystery'):
            thriller.append(movie)
        if(g=='Adventure'):
            adventure.append(movie)
        if(g=='Comedy'):
            comedy.append(movie)
        if(g=='Horror'):
            horror.append(movie)
        if(g=='Biography' or g=='History'):
            biography.append(movie)
        if(g=='Animation' or g=='Fantasy'):
            animation.append(movie)
        if(g=='Sci-Fi'):
            scifi.append(movie)
        if(g=='Romance'):
            romance.append(movie)
        else:
            others.append(movie)

In [30]:
print(scifi)

['Guardians of the Galaxy', 'Prometheus', 'Rogue One', 'Arrival', 'Independence Day: Resurgence', 'X-Men: Apocalypse', 'Resident Evil: The Final Chapter', 'Captain America: Civil War', 'Interstellar', 'Star Trek Beyond', 'Batman v Superman: Dawn of Justice', 'The Prestige', 'Mad Max: Fury Road', 'The Avengers', 'Inception', 'Jurassic World', 'Avengers: Age of Ultron', 'The Void', 'The Martian', 'Ex Machina', 'The Bad Batch', 'Divergent', 'Transformers: Age of Extinction', 'Star Trek', 'The Hunger Games', 'Aliens vs Predator - Requiem', 'Pacific Rim', 'X-Men: Days of Future Past', 'Her', 'Realive', 'Morgan', 'Captain America: The First Avenger', 'Edge of Tomorrow', 'Iron Man', 'X: First Class', 'Transformers', 'Captain America: The Winter Soldier', 'Hardcore Henry', 'Predators', 'Rupture', 'Terminator Genisys', 'Children of Men', 'The Amazing Spider-Man 2', 'Battleship', 'Rise of the Planet of the Apes', 'Cloud Atlas', 'X-Men Origins: Wolverine', 'Iron Man Three', 'Jupiter Ascending', 'Snowpiercer', 'The 5th Wave', 'In Time', 'Victor Frankenstein', 'Insurgent', 'Star Trek Into Darkness', 'Sleight', 'The Maze Runner', 'The Wolverine', 'John Carter', 'The Incredible Hulk', 'Absolutely Anything', 'The Hunger Games: Mockingjay - Part 2', 'The Purge: Election Year', 'Dredd', 'Iron Man 2', 'I Am Number Four', 'Predestination', 'District 9', '2012', 'The Giver', 'Stake Land', 'Cloverfield', 'Under the Skin', 'I Am Legend', 'Super 8', 'Maze Runner: The Scorch Trials', 'Gravity', 'The Happening', 'Elysium', 'Godzilla', 'Deja Vu', 'Lucy', 'Limitless', 'Spectral', 'Midnight Special', 'Fantastic Four', 'The Survivalist', 'Idiocracy', 'Transformers: Dark of the Moon', 'Tron', 'Sunshine', 'Moon', "2307: Winter's Dream", 'Source Code', 'Viral', 'Green Lantern', 'The Hunger Games: Mockingjay - Part 1', 'Jumper', 'Resident Evil: Retribution', 'I Origins', 'The Adjustment Bureau', 'Transformers: Revenge of the Fallen', 'Paul', 'The Purge', "Ender's Game", 'The Fountain', 'Self/less', "The World's End", 'G.I. Joe: The Rise of Cobra', '28 Weeks Later', 'G.I. Joe: Retaliation', 'Equals', 'RoboCop', 'Slither', 'Coherence', 'Superman Returns', 'Riddick', 'After Earth', 'Death Race', 'Into the Forest']

In [31]:
#surprise for scifi
rating=[]
for movie in scifi:
    r=int(df.loc[df['Title']==movie,'Rating'])
    m=int(df.loc[df['Title']==movie,'Metascore'])
    score=(r*0.3)+(m*0.7)
    v=int(df.loc[df['Title']==movie,'Votes'])
    if(r>7):
        movie_score=(v/20000)*score #opularity score where movies with rating more than 7  and more than 200000 votes lead to a better score
        rating.append(movie_score)
    else:
        movie_score=score+0.07*v
        rating.append(movie_score)

In [34]:
scifi_final=list(zip(rating,scifi))
scifi_final[45][1]

'Cloud Atlas'

In [33]:
scifi_final.sort()

In [13]:
#prints the top 20 movies with the most popularity scores
print(scifi_final[100:])

[(28395.780000000002, 'Source Code'), (28870.52, 'Captain America: Civil War'), (29288.910000000003, 'Star Trek Into Darkness'), (29610.000000000004, 'Rise of the Planet of the Apes'), (31152.590000000004, 'Limitless'), (31905.230000000003, 'Jurassic World'), (33078.850000000006, 'Edge of Tomorrow'), (33094.090000000004, 'Batman v Superman: Dawn of Justice'), (34055.0, 'Prometheus'), (36230.950000000004, 'Avengers: Age of Ultron'), (37222.64000000001, 'Transformers'), (38016.44, 'Captain America: The Winter Soldier'), (38363.76, 'Captain America: The First Avenger'), (38548.37, 'X: First Class'), (39008.62, 'Iron Man 2'), (39648.07, 'I Am Legend'), (41417.11, 'Iron Man Three'), (43615.530000000006, 'Gravity'), (51541.98, 'The Hunger Games'), (51697.73, 'Iron Man')]